# config.py (correto)
SQLALCHEMY_DATABASE_URI = 'mysql+mysqlconnector://root:TFiwsudwtErlsvfYKIOntCLpFYnIoqMq@caboose.proxy.rlwy.net:16652/railway'
SQLALCHEMY_TRACK_MODIFICATIONS = False
